language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - GLOBAL_VAR1=wartość1

cache: pip

install:
  - pip install -r tests/requirements.txt
  - pip install -e .

script:
  - python -m unittest tests/*
